### ISSUE TITLE
建议数据脱敏处理

### ISSUE THREAD

**Issue by AIDefender** [EricZhu-42/PedagogySquare_Downloader#1]
把zyz老师的名字打个码啥的

**Comment by EricZhu-42** [comment]
噢噢噢是的 我确实没注意到这点 现在就来改

2020-03-31 17:10 GMT+08:00, Zheng H. Xue <notifications@github.com>:
> 把zyz老师的名字打个码啥的

>

> --

> You are receiving this because you are subscribed to this thread.

> Reply to this email directly or view it on GitHub:

> https://github.com/EricZhu-42/PedagogySquare_Downloader/issues/1


-- 
朱鑫浩
南京大学 人工智能学院 本科生

Xinhao ZHU
Undergraduate Student
School of Artificial Intelligence, Nanjing University

**Comment by EricZhu-42** [comment]
谢谢反馈！

2020-03-31 17:10 GMT+08:00, Zheng H. Xue <notifications@github.com>:
> 把zyz老师的名字打个码啥的

>

> --

> You are receiving this because you are subscribed to this thread.

> Reply to this email directly or view it on GitHub:

> https://github.com/EricZhu-42/PedagogySquare_Downloader/issues/1


-- 
朱鑫浩
南京大学 人工智能学院 本科生

Xinhao ZHU
Undergraduate Student
School of Artificial Intelligence, Nanjing University

**Comment by AIDefender** [comment]
:)
