### ISSUE TITLE
提个小bug与我的修复

### ISSUE THREAD

**Issue by Price1999a** [EricZhu-42/PedagogySquare_Downloader#2]
简单来讲我配置成这样时
```
"headless_mode": true,
"download_all_ext": true,
"download_all_courses": false,
"ext_list": [],
"ext_expel_list": [],
"cid_list": [5292]
```
cid_list是从配置中读取的 数据类型是int
而cid2name_dict这个dict中的key是str类型的
换言之
```
for cid in cid_list:
    course_name = cid2name_dict[cid]
```
会因为找不到key异常（python 3.7.0）
我做出了一个小改动修正它
```
for cid in cid_list:
    course_name = cid2name_dict[str(cid)]
```
这个改动不提pr了

**Comment by EricZhu-42** [comment]
你好！感谢你的反馈！

事实上，在不久前有同学向我反映了相同的问题。因此，在上一次[commit](https://github.com/EricZhu-42/PedagogySquare_Downloader/commit/1598c52673f35c69239274f0e638b10831983228)中，已经修正了这个问题。（使用了基本相同的方法，加了一行cid = str(cid)）

再次感谢！
